
application_name_alnum: "{{ application_name | regex_replace('[^a-zA-Z0-9]') }}"

QueueName: "{{ application_name_alnum }}-{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
